#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_app="0.0.1"
  jq -n --arg fogg_app "$ver_fogg_app" '{fogg_app: $fogg_app}'
}

version "$@"
